### PR TITLE
Changes from O.S. Systems

### PR DESCRIPTION
**Pull request by otavio**

### CODE REVIEW

**Comment by dubek** [comment]
Thank you for the contributions. I will soon find some time to review the PR.

**Comment by dubek** [comment]
Thanks @otavio , the changes look good. Thank you for adding the Docker image recipe. If you want, I'd appreciate an addition to the README with instructions on building and using the Docker image (with the env vars you used in `entrypoint.sh`).

**Comment by dubek** [comment]
One comment: you may remove `libev-dev` from the `apk add` line, because goldy downloads and builds its own copy of libev during `make deps`.

**Comment by otavio** [comment]
We will document how to use it and provide a new PR. Thanks for merging this.

**Pull request merged**
